---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.9

inputs:
- name: git
  path: src/github.com/stefancocora/awsctl

params:
  SRC_PATH: src/github.com/stefancocora/awsctl
  HTTP_PROXY: http://pkgcacher.internal:3128
  HTTPS_PROXY: http://pkgcacher.internal:3128

run:
  path: sh
  args:
    - "-exc"
    - |
      id
      echo "=== debugging"
      echo "HTTP_PROXY: $HTTP_PROXY"
      echo "HTTPS_PROXY: $HTTPS_PROXY"
      apt-get update
      apt-get install -y bash file make
      echo "pwd: $PWD"
      echo "initial gopath: $GOPATH"
      printf "go version: "
      go version
      printf "make version: "
      make --version | sed -e "2,5d"
      echo "=== debugging"
      echo ""
      echo "=== re-setting GOPATH"
      export GOPATH=$PWD
      export PATH=$GOPATH/bin:$PATH
      echo "re-set gopath: $GOPATH"
      cd $SRC_PATH
      make unit
