---
groups:
  - name: awsctl_gh_branch
    jobs:
    - unit
    - create-rc
    - major
    - minor
    - patch

jobs:
- name: major
  serial_groups: [version]
  public: true
  plan:
  - get: version
    params:
      bump: major
      pre: rc
  - put: version
    params:
      file: version/number
- name: minor
  serial_groups: [version]
  public: true
  plan:
  - get: version
    params:
      bump: minor
      pre: rc
  - put: version
    params:
      file: version/number

- name: patch
  serial_groups: [version]
  plan:
  - get: version
    params:
      bump: patch
      pre: rc
  - put: version
    params:
      file: version/number

- name: unit
  public: true
  plan:
    - aggregate:
      - get: git
        trigger: true
      - get: golang_1.9
    - aggregate:
      - task: unit
        file: git/ci/tasks/unit.yml

- name: create-rc
  public: true
  serial: true
  serial_groups: [version]
  plan:
    - aggregate:
      - get: git
        trigger: true
        passed: [unit]
      - get: golang_1.9
      - get: version
        params: {pre: rc}
    - aggregate:
      - task: display_version
        image: golang_1.9
        config:
          platform: linux
          inputs:
          - name: version
          run:
            path: sh
            args:
              - "-exc"
              - |
                id
                ls -lha
                ls -lha version/number
                cat version/number
      - task: unit
        file: git/ci/tasks/unit.yml
      - task: build
        file: git/ci/tasks/build_branch.yml
    - aggregate:
      - put: version
        params: {pre: rc}
      - put: awsctl-rc
        params:
          file: tarball/awsctl-*.gz


# resources
resources:
- name: golang_1.9
  type: docker-image
  source:
    repository: golang
    tag: 1.9

- name: git
  type: git
  source:
    uri: https://github.com/stefancocora/awsctl.git
    branch: feature/add_license
    every: true

- name: version
  type: semver
  source:
    driver: git
    uri: git@gogs-gogs.default.svc.cluster.local:stefan/awsctl.git
    private_key: ((git_ssh_priv))
    branch: version
    file: ci/version
    initial_version: "0.0.1"

- name: awsctl_gh-rc
  type: s3
  source:
    bucket: awsctl-gh-rc
    regexp: awsctl-(.*)
    access_key_id: ((awsctl_rc_access_key))
    secret_access_key: ((awsctl_rc_secret_key))
    endpoint: http://minio-minio-svc.default.svc.cluster.local:9000
    disable_ssl: true
    use_v4: true
